### ISSUE TITLE
Cardinality is swapped?

### ISSUE THREAD

**Issue by saulcruzr** [laowantong/mocodo#45]
This is a very awesome library and I'm sure it has a lot of potential. 

I've been playing around with it and noticed that the cardinality is swapped? for example, I was using it for a data warehouse model and noticed that the cardinality from a dimension to a fact which is usually one to many (1,1 to 1,N)  was incorrectly generating foreign keys in the dimension table (1,1).

In other words I was following the following specification:

https://www.ibm.com/support/knowledgecenter/en/SSEP7J_10.1.0/com.ibm.swg.im.cognos.ug_fm.10.1.0.doc/ug_fm_id20561bp-modeling_relational_data_sources.html

![image](https://user-images.githubusercontent.com/3718514/60699311-4aa95980-9ec1-11e9-8a7f-cdbd4723d975.png)

Is there any reason why the cardinalities are swapped?

**Comment by laowantong** [comment]
Interesting question. The reason the cardinalities are “swapped“ is that Mocodo implements the conventions of the so-called MCD (Conceptual model of data), a part of a more general method called [Merise](https://en.wikipedia.org/wiki/Merise). Nowadays, Merise is as good as dead, but this part survives in the French-speaking world. It is still taught at university in introductory DB courses, since it has some pedagogical advantages over UML. Swapping the cardinalities as no impact for a binary relation, but things change as soon as you have a ternary relation. In such cases, the MCD convention is arguably better, since UML requires that you swap the cardinalities again or avoid them altogether (it is always possible to replace a n-ary relation with n or n-1 binary relations, depending on the cardinalities).
